import type { Post } from '../types/content'

export const seedPosts: Post[] = [
  {
    id: 'post-ai-agents',
    slug: 'ai-agents-rewriting-software',
    title: 'How AI Agents Are Rewriting Software',
    dek: 'The shift from assistants to autonomous systems is changing how digital products are designed, built and maintained.',
    category: 'Artificial Intelligence',
    date: 'September 13, 2026',
    readTime: '8 min read',
    image: 'https://picsum.photos/seed/agentic-future/1800/1200',
    author: 'The Living Journal',
    featured: true,
    trending: true,
    status: 'published',
    tags: ['AI', 'Agents', 'Software'],
    seoTitle: 'How AI Agents Are Rewriting Software',
    metaDescription: 'A practical look at how agentic software changes product design, engineering and maintenance.',
    sections: [
      { type: 'paragraph', text: 'The most important shift in software is not that machines can write more code. It is that software is beginning to participate in the work itself.' },
      { type: 'paragraph', text: 'For years, digital tools waited for explicit instructions. A user clicked, typed, selected and confirmed every meaningful action. The new generation of systems is different: they can observe context, form a plan, use tools and continue work across several steps.' },
      { type: 'heading', text: 'From interface to collaborator' },
      { type: 'paragraph', text: 'That changes the design problem. Instead of asking how users navigate a workflow, teams have to decide what work the system can safely perform, what evidence it should show, where approval belongs and how people recover when automation is wrong.' },
      { type: 'quote', text: 'The interface of the future may be less about navigating software and more about supervising intent.' },
      { type: 'image', src: 'https://picsum.photos/seed/agent-workflow/1500/900', alt: 'Abstract visualization of a connected workflow', caption: 'Agentic products compress several user actions into one supervised outcome.' },
      { type: 'heading', text: 'The new engineering surface' },
      { type: 'paragraph', text: 'Engineering teams are now responsible for orchestration, tool boundaries, permissions, memory, evaluations and observability alongside traditional application concerns. Reliability is no longer only about whether a request succeeds. It is also about whether the system chose the right sequence of actions.' },
      { type: 'paragraph', text: 'The companies that win will not simply attach a model to existing software. They will redesign products around a new assumption: software can act.' },
    ],
  },
  {
    id: 'post-careers-2027',
    slug: 'developer-careers-2027',
    title: 'What Developers Should Learn Before 2027',
    dek: 'A practical field guide to the skills becoming more valuable as AI absorbs repetitive implementation work.',
    category: 'Career',
    date: 'September 12, 2026',
    readTime: '7 min read',
    image: 'https://picsum.photos/seed/developer-career/1600/1100',
    author: 'The Living Journal',
    trending: true,
    status: 'published',
    tags: ['Career', 'Development', 'AI'],
    sections: [
      { type: 'paragraph', text: 'The safest career strategy is no longer collecting frameworks. It is becoming good at turning ambiguous product problems into reliable systems.' },
      { type: 'heading', text: 'Depth matters again' },
      { type: 'paragraph', text: 'AI can generate plausible code quickly, but experienced engineers still need to reason about architecture, data integrity, security, performance and the hidden cost of shortcuts.' },
      { type: 'quote', text: 'Use AI to move faster, but build the judgment required to know when fast is wrong.' },
    ],
  },
  {
    id: 'post-small-teams',
    slug: 'small-teams-big-products',
    title: 'Why Small Teams Are Building Bigger Products',
    dek: 'Better tooling is compressing the distance between an idea and a production-grade product.',
    category: 'Business',
    date: 'September 11, 2026',
    readTime: '6 min read',
    image: 'https://picsum.photos/seed/small-team/1600/1100',
    author: 'The Living Journal',
    trending: true,
    status: 'published',
    tags: ['Business', 'Teams', 'Product'],
    sections: [
      { type: 'paragraph', text: 'A five-person team can now operate with leverage that once required several departments. The change is not only AI; it is the accumulation of better infrastructure, APIs, design systems and distribution tools.' },
      { type: 'heading', text: 'Leverage changes the org chart' },
      { type: 'paragraph', text: 'When execution gets cheaper, clarity becomes more valuable. Small teams are strongest when product ownership is close to implementation and decisions move with very little translation loss.' },
    ],
  },
  {
    id: 'post-react',
    slug: 'react-after-server-components',
    title: 'React After Server Components',
    dek: 'The frontend mental model is moving again. Here is what that means for product teams.',
    category: 'Development',
    date: 'September 10, 2026',
    readTime: '9 min read',
    image: 'https://picsum.photos/seed/react-future/1600/1100',
    author: 'The Living Journal',
    status: 'published',
    tags: ['React', 'Frontend', 'Architecture'],
    sections: [
      { type: 'paragraph', text: 'Frontend architecture is increasingly a question of deciding where work belongs rather than assuming everything belongs in the browser.' },
      { type: 'heading', text: 'A boundary, not a doctrine' },
      { type: 'paragraph', text: 'Server Components are useful when teams treat them as a boundary for data and rendering rather than as a reason to rebuild every interaction around a new abstraction.' },
    ],
  },
  {
    id: 'post-ai-economics',
    slug: 'economics-of-ai-startups',
    title: 'The New Economics of AI Startups',
    dek: 'Infrastructure gets cheaper, distribution gets harder, and taste becomes a competitive advantage.',
    category: 'Startups',
    date: 'September 9, 2026',
    readTime: '10 min read',
    image: 'https://picsum.photos/seed/startup-economics/1600/1100',
    author: 'The Living Journal',
    trending: true,
    status: 'published',
    tags: ['Startups', 'AI', 'Economics'],
    sections: [
      { type: 'paragraph', text: 'The cost of building software continues to fall, but the cost of earning attention is moving in the opposite direction.' },
      { type: 'heading', text: 'Distribution is the moat' },
      { type: 'paragraph', text: 'When features can be copied quickly, companies need stronger distribution, proprietary context, better workflows or a brand people actively choose.' },
    ],
  },
  {
    id: 'post-design-systems',
    slug: 'design-systems-need-less-components',
    title: 'Design Systems Need Fewer Components, Not More',
    dek: 'A smaller vocabulary can create more coherent products when teams invest in composition instead of endless variants.',
    category: 'Development',
    date: 'September 8, 2026',
    readTime: '5 min read',
    image: 'https://picsum.photos/seed/design-system/1600/1100',
    author: 'The Living Journal',
    status: 'published',
    tags: ['Design Systems', 'UI', 'Frontend'],
    sections: [
      { type: 'paragraph', text: 'Mature design systems often become catalogs of historical exceptions. That makes them harder to learn, harder to maintain and harder to evolve.' },
      { type: 'heading', text: 'Composition scales better than configuration' },
      { type: 'paragraph', text: 'A compact set of primitives with clear constraints usually outlives a massive library of one-off components.' },
    ],
  },
]
